# Chapter 6.1.2 - Using word embeddings

# Embedding layer with Keras

In [1]:
import keras

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
keras.__version__

'2.1.3'

In [3]:
from keras.layers import Embedding

# Number of maximum tokens is equal of maximum word index + 1
max_number_of_tokens = 1000
embedding_dimentionality = 64
embedding_layer = Embedding(max_number_of_tokens, embedding_dimentionality)

The layers transforms a 2D input tensor of integer of shape (number_of samples, sequence_length) into a 3D floating point tensor, of shape (number_of_samples, sequence_length, embedding_dimensionality.)
Such tensor can be processed a RNN layer of a 1D convolutional layer.

## IMDB example

In [4]:
from keras.datasets import imdb
from keras.preprocessing.sequence import pad_sequences

In [5]:
# Number of words considered as features
max_features = 10000

In [6]:
# Cutting reviews after only 20 words
sequence_max_length = 20

In [7]:
# Loading data
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words = max_features)

In [8]:
x_train.shape

(25000,)

In [9]:
x_train_sequence = pad_sequences(x_train, maxlen = sequence_max_length)

In [10]:
x_train_sequence.shape

(25000, 20)

In [11]:
x_train[0:2]

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [12]:
x_train[0].__getitem__(-20)

65

In [13]:
x_train_sequence[0, :]

array([  65,   16,   38, 1334,   88,   12,   16,  283,    5,   16, 4472,
        113,  103,   32,   15,   16, 5345,   19,  178,   32])

In [14]:
x_train_sequence[0]

array([  65,   16,   38, 1334,   88,   12,   16,  283,    5,   16, 4472,
        113,  103,   32,   15,   16, 5345,   19,  178,   32])

In [15]:
x_train_sequence[1]

array([  23,    4, 1690,   15,   16,    4, 1355,    5,   28,    6,   52,
        154,  462,   33,   89,   78,  285,   16,  145,   95])

# Model

In [16]:
from keras.models import Sequential
from keras.layers import Flatten, Dense

In [17]:
model = Sequential()
model.add(Embedding(input_dim = max_features, output_dim = 8, input_length = sequence_max_length))
model.add(Flatten())
model.add(Dense(units = 1, activation = 'sigmoid'))

In [18]:
# Compiling the model
model.compile(optimizer = 'rmsprop', 
              loss = 'binary_crossentropy', 
              metrics = ['acc'])

In [19]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 8)             80000     
_________________________________________________________________
flatten_1 (Flatten)          (None, 160)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 161       
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


In [20]:
# Training
history = model.fit(x = x_train_sequence, 
                    y = y_train, 
                    epochs = 10, 
                    batch_size = 32, 
                    validation_split = 0.2)

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 7s 325us/step - loss: 0.6759 - acc: 0.6050 - val_loss: 0.6398 - val_acc: 0.6814
Epoch 2/10
20000/20000 [==============================] - 4s 222us/step - loss: 0.5657 - acc: 0.7427 - val_loss: 0.5467 - val_acc: 0.7206
Epoch 3/10
20000/20000 [==============================] - 5s 226us/step - loss: 0.4752 - acc: 0.7808 - val_loss: 0.5113 - val_acc: 0.7384
Epoch 4/10
20000/20000 [==============================] - 5s 228us/step - loss: 0.4263 - acc: 0.8077 - val_loss: 0.5008 - val_acc: 0.7452
Epoch 5/10
20000/20000 [==============================] - 4s 219us/step - loss: 0.3930 - acc: 0.8258 - val_loss: 0.4981 - val_acc: 0.7538
Epoch 6/10
20000/20000 [==============================] - 4s 195us/step - loss: 0.3668 - acc: 0.8395 - val_loss: 0.5014 - val_acc: 0.7530
Epoch 7/10
20000/20000 [==============================] - 4s 197us/step - loss: 0.3435 - acc: 0.8533 - val_loss: 0.5052 - v

# Using pre-trained word embeddings

The data can be downloaded from: http://mng.bz/0tIo

In [21]:
import os

In [22]:
imdb_dir = './data/Chapter 6.1.2 - Using word embeddings/aclImdb/'

In [ ]:
train_dir = os.path.join(imdb_dir, 'train')

In [ ]:
labels = []
texts = []

for label_type in ['neg', 'pos']:
    dir_name = os.path.join(train_dir, label_type)
    for fname in os.listdir(dir_name):
        # Taking into consideration files which are only .txt
        if fname[-4:] == '.txt':
            f = open(os.path.join(dir_name, fname), encoding="utf8")
            texts.append(f.read())
            f.close()
            if label_type == 'neg':
                labels.append(0)
            else:
                labels.append(1)

In [ ]:
len(labels)

In [ ]:
len(texts)

In [ ]:
texts[0]

In [ ]:
labels[0]

# Tokenizing the data

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

In [ ]:
# Using only first 100 words of each review
maxlen = 100

In [ ]:
# Number of training samples
training_samples = 200

In [ ]:
# Number of validation samples
validation_samples = 10000

In [ ]:
# Tokenizing only top 10 000 words in the dataset.
max_words = 10000 

In [ ]:
# Initializing Tokenizer
tokenizer = Tokenizer(num_words = max_words)

In [ ]:
# Fitting the Tokenizer on the text
tokenizer.fit_on_texts(texts)

In [ ]:
# Text to sequence
sequences = tokenizer.texts_to_sequences(texts)

In [ ]:
sequences[0:2]

In [ ]:
# Word index
word_index = tokenizer.word_index

In [ ]:
type(word_index)

In [ ]:
first10pairs = {k: word_index[k] for k in list(word_index)[:10]}

In [ ]:
first10pairs

In [ ]:
# Padding the sequence
data = pad_sequences(sequences, maxlen = maxlen)

In [ ]:
data.shape

In [ ]:
labels = np.asarray(labels)

In [ ]:
labels.shape

In [ ]:
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]

In [ ]:
# Splitting the data into train and validation datasets
x_train = data[:training_samples]
y_train = labels[:training_samples]
x_val = data[training_samples: training_samples + validation_samples]
y_val = labels[training_samples: training_samples + validation_samples]

In [ ]:
x_train.shape

In [ ]:
x_val.shape

## GloVe Embedding

Download from: http://nlp.stanford.edu/data/glove.6B.zip

In [ ]:
# Importing tqdm to show a progress bar
from tqdm import tqdm

In [ ]:
glove_dir = './data/Chapter 6.1.2 - Using word embeddings/glove.6B/'
embeddings_index = {}
f = open(os.path.join(glove_dir, 'glove.6B.100d.txt'), 
         encoding = 'utf-8')
for line in tqdm(f):
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], 
                       dtype = 'float32')
    embeddings_index[word] = coefs
f.close()

In [ ]:
len(embeddings_index)

In [ ]:
embedding_dim = 100
embedding_matrix = np.zeros((max_words, embedding_dim))

for word, i in word_index.items():
    if i < max_words:
        embedding_vector = embeddings_index.get(word)
        # Words not found in the embedding index will be represented as zeros
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [ ]:
embedding_matrix

## Model

In [ ]:
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense

In [ ]:
model = Sequential()
model.add(Embedding(input_dim = max_words, 
                    output_dim = embedding_dim, 
                    input_length = maxlen))
model.add(Flatten())
model.add(Dense(units = 32, 
                activation = 'relu'))
model.add(Dense(units = 1, 
                activation = 'sigmoid'))
model.summary()

In [ ]:
# Loading pretrained word embeddings
model.layers[0].set_weights([embedding_matrix])
# Freezing the layer
model.layers[0].trainable = False